NAME=main
TAG=$(NAME)
VER=v1.0

all: clean generate build 

build:
	go build main.go # Should we give Auto generated file here ??
clean:
	rm -rf $(NAME)
generate:
	go generate  # Autogenerated .go files. These are used in build
